# Generated by Django 4.0.1 on 2022-01-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название блюда')),
                ('description', models.CharField(max_length=500, verbose_name='Орисание блюда')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость блюда')),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='Вес блюда')),
                ('calories', models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='Калории')),
                ('vegan', models.BooleanField(default=False, verbose_name='Вегитарианская')),
                ('order_days', models.CharField(max_length=2, verbose_name='Дни для заказа')),
                ('allow_order', models.BooleanField(default=True, verbose_name='Разрешено для заказа')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now=True, verbose_name='Дата заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('order_date', 'customer__last_name', 'customer__first_name', 'customer__patronymic'),
            },
        ),
        migrations.CreateModel(
            name='OrderTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Время начала приёма заказов')),
                ('end_time', models.TimeField(verbose_name='Время окончания приёма заказов')),
            ],
        ),
        migrations.CreateModel(
            name='TypeFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Тип блюда')),
            ],
        ),
    ]
