# Generated by Django 4.0.1 on 2022-01-28 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(unique=True, verbose_name='Дата поставки')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название блюда')),
                ('description', models.CharField(max_length=500, verbose_name='Описание блюда')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость блюда')),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='Вес блюда')),
                ('calories', models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='Калории')),
                ('vegan', models.BooleanField(default=False, verbose_name='Вегитарианская')),
                ('delivery_days', models.ManyToManyField(blank=True, related_name='dishes', to='dishes.DeliveryDate', verbose_name='Дни для заказа')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OrderTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала приёма заказов')),
                ('end_time', models.TimeField(verbose_name='Время окончания приёма заказов')),
            ],
            options={
                'verbose_name': 'Ограничение времени заказов',
                'verbose_name_plural': 'Ограничение времени заказов',
            },
        ),
        migrations.CreateModel(
            name='TypeFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Тип блюда')),
            ],
            options={
                'verbose_name': 'Тип блюда',
                'verbose_name_plural': 'Типы блюд',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(verbose_name='Дата поступления заказа')),
                ('order_date', models.DateField(auto_now=True, verbose_name='Дата оформления заказа')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
                ('dish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='dishes.dish', verbose_name='Блюда')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('delivery_date', 'customer__last_name', 'customer__first_name', 'customer__patronymic'),
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='type_food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='dishes.typefood', verbose_name='Тип блюда'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('dish', 'customer', 'delivery_date'), name='Разрешён один заказ в день.'),
        ),
    ]
