# Generated by Django 4.0.1 on 2022-01-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertime',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала приёма заказов'),
        ),
    ]
