# Generated by Django 4.0.1 on 2022-01-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_alter_ordertime_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordertime',
            options={'verbose_name': 'Ограничение времени заказов', 'verbose_name_plural': 'Ограничение времени заказов'},
        ),
    ]
